[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.psram_type = opi

; Enable PSRAM
board_build.arduino.memory_type = qio_opi

build_flags = 
    -DCORE_DEBUG_LEVEL=5
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    esp32-camera
    WiFi


; Partition scheme for larger programs and SPIFFS
board_build.partitions = huge_app.csv

; Uncomment and modify if you need a specific upload port
upload_port = /dev/cu.wchusbserial59590864361

; upload_flags = 
;     --before=default_reset
;     --after=hard_reset
;     --connect-attempts=5
