Auto_pitch: true
Auto_vel: true
Auto_yaw: true
Direction_pitch: false
Direction_vel: true
Direction_yaw: true
Kd_pitch: 1.1
Kd_vel: 0.5
Kd_yaw: 0.0
Ki_pitch: 50.0
Ki_vel: 20.0
Ki_yaw: 4.0
Kp_pitch: 40.0
Kp_vel: 15.0
Kp_yaw: 3.0
LW_threshold: 45
Max_pitch: 255.0
Max_vel: 4.0
Max_yaw: 200.0
Min_pitch: -255.0
Min_vel: -4.0
Min_yaw: -200.0
Period_pitch: 7
Period_vel: 210
Period_yaw: 187
RW_threshold: 45
TicKs_p_r: 293
