Auto_pitch: true
Auto_vel: true
Auto_yaw: true
Direction_pitch: false
Direction_vel: true
Direction_yaw: true
Kd_pitch: 0.8
Kd_vel: 0.0
Kd_yaw: 0.0
Ki_pitch: 50.0
Ki_vel: 15.0
Ki_yaw: 4.0
Kp_pitch: 30.0
Kp_vel: 12.0
Kp_yaw: 5.0
LW_threshold: 70
Max_pitch: 255.0
Max_vel: 4.0
Max_yaw: 200.0
Min_pitch: -255.0
Min_vel: -4.0
Min_yaw: -200.0
Period_pitch: 12
Period_vel: 50
Period_yaw: 50
RW_threshold: 70
TicKs_p_r: 293
