[env:esp-wrover-kit]
platform = espressif32@6.10.0
board = esp-wrover-kit
framework = arduino
lib_deps =
    powerbroker2/ArduPID
    powerbroker2/FireTimer
    tcmenu/tcMenu
    olikraus/U8g2
    tcmenu/IoAbstraction
    tcmenu/tcUnicodeHelper  
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor
    https://github.com/sparkfun/SparkFun_TB6612FNG_Arduino_Library.git
   # simsso/ShiftRegister74HC595@^1.3.1
build_src_filter = 
    +<*> 
    -<menu/>
    -<backup/>

build_flags = 
    -D USE_PSRAM=1
    -D SERIAL_DEBUG
monitor_speed = 115200
board_build.partitions = default.csv
upload_speed = 921600